### ISSUE TITLE
Outputs don't seem to be there

### ISSUE THREAD

**Issue by peoplespete** [DSACMS/automated-codejson-generator#33]
Hi! First of all, thank you so much for building this! 

I'm on MDCT and it works awesome as intended. I tried to automate further so that it would automate the merging of the PR this project produces. There are some issues related to that that I've hit but in the process of bumbling around I noticed that this file:
https://github.com/DSACMS/automated-codejson-generator/blob/main/action.yml
made me think that I could expect outputs:
```yml
outputs:
  updated:
    description: "Boolean indicating whether code.json was updated"
  pr_url:
    description: "URL of the created pull request if changes were made"
```
to be present such that in my own update-code-json.yml file I could do something like this:
```yml
name: Update Code.json
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # monthly on day 1

permissions:
  contents: write
  pull-requests: write

jobs:
  update-code-json:
    runs-on: ubuntu-latest
    steps:

       ...

      - name: Update code.json
        id: update
        uses: DSACMS/automated-codejson-generator@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: "main"

      - name: Print PR url
        run: |
          echo "${{steps.update.outputs.pr_url}}"
```
It's not stopping me anymore because I got something like this thrown together:
```yml
      - name: Print PR url
        run: |
          PR_URL=$(gh pr list --state open --json url,headRefName \
            --jq '.[] | select(.headRefName | startswith("code-json-")) | .url' \
            | head -n 1)
          echo "Found PR: $PR_URL"
```
Feel free to remove or close this issue if it isn't helpful and thanks again for building this, it's been super helpful!

**Comment by sachin-panayil** [comment]
@peoplespete thank you for this! this was supposed to work how you intented it to orignally where you could easily output the PR URL but i will take a look at fixing this. Im also curious as to what the auto merge workflow you built looks like as it could potentially be added onto the project and turned on and off with a flag

**Comment by peoplespete** [comment]
Weeeeeeell I didn't end up being able to do it but here's what I wanted to do:

```yml
name: Update Code.json
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # monthly on day 1

permissions:
  contents: write
  pull-requests: write

jobs:
  update-code-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: "20"

      - name: Setup Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: "1.22"

      - name: Install SCC
        run: go install github.com/boyter/scc/v3@v3.5.0

      - name: Update code.json
        id: update
        uses: DSACMS/automated-codejson-generator@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: "master"

      - name: Approve and enable auto-merge PR
        run: |
          PR_URL=$(gh pr list --state open --json url,headRefName \
            --jq '.[] | select(.headRefName | startswith("code-json-")) | .url' \
            | head -n 1)
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{secrets.GLOBAL_GH_PAT}}
```

The idea was that I could find the PR this repo generates and then approve and merge it programmatically. The first problem I hit was that because of some branch protections that required certain other workflows to pass before merging. So then I thought ok fine we'll do what I've pasted above. That basically says, approve and merge it automatically once conditions are met. But that didn't work. Because Github doesn't let your branch's (code-json-TIMESTAMP) creation trigger our deployment Github workflow which needs to run to meet branch protection blockers. It seems to be a rule they have to keep automation from becoming too out of control. Then I also tried to find a way to force the merge or get around the branch condition with a Github Personal Access Token from an admin account, but that seemed to also be blocked by something (potentially an Organization level rule I can't see).

So for now I gave up :(

But if you know of a way to pull this off or any way to automatically commit these changes to main/master, I'm all ears.
